name: k6 accelerator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/**
      - bugfix/**
      - chore/**

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install packages
        run: npm ci
      - name: Run NestJS API
        run: npm run api:start
      - name: Build xk6
        run: npm run k6:xk6-dashboard:build
      - name: Run k6 Tests
        run: |
          npm run k6:performance:tests && npm run k6:positive:tests && npm run k6:negative:tests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: k6-html-test-reports
          path: |
            ./src/test/k6/k6-performance-test-report.html
            ./src/test/k6/k6-positive-test-report.html
            ./src/test/k6/k6-negative-test-report.html
          retention-days: 3
